// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// fitglmm_ai
List fitglmm_ai(arma::vec Y, arma::mat X, size_t q, List Phi, size_t ng, List group, arma::vec W, arma::vec tau, arma::uvec fixtau);
RcppExport SEXP _GMMAT_fitglmm_ai(SEXP YSEXP, SEXP XSEXP, SEXP qSEXP, SEXP PhiSEXP, SEXP ngSEXP, SEXP groupSEXP, SEXP WSEXP, SEXP tauSEXP, SEXP fixtauSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type Y(YSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< size_t >::type q(qSEXP);
    Rcpp::traits::input_parameter< List >::type Phi(PhiSEXP);
    Rcpp::traits::input_parameter< size_t >::type ng(ngSEXP);
    Rcpp::traits::input_parameter< List >::type group(groupSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type W(WSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type fixtau(fixtauSEXP);
    rcpp_result_gen = Rcpp::wrap(fitglmm_ai(Y, X, q, Phi, ng, group, W, tau, fixtau));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_GMMAT_fitglmm_ai", (DL_FUNC) &_GMMAT_fitglmm_ai, 9},
    {NULL, NULL, 0}
};

RcppExport void R_init_GMMAT(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
