# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fitglmm_ai <- function(Y, X, q, Phi, ng, group, W, tau, fixtau) {
    .Call('_GMMAT_fitglmm_ai', PACKAGE = 'GMMAT', Y, X, q, Phi, ng, group, W, tau, fixtau)
}

